# Generated by Django 3.2.4 on 2021-06-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='group_id',
        ),
        migrations.AddField(
            model_name='student',
            name='grades_sum',
            field=models.IntegerField(default=0, verbose_name='Сума балів'),
        ),
    ]
