# Generated by Django 3.2.4 on 2021-06-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_group_student_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Тема лекції')),
                ('description', models.TextField(max_length=90, verbose_name='Опис лекції')),
                ('attachments', models.FileField(upload_to='files/lectures/', verbose_name='Матеріали')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='main.group')),
            ],
            options={
                'verbose_name': 'Лекція',
                'verbose_name_plural': 'Лекції',
                'db_table': 'tb_lectures',
            },
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
